PROG=proj

SRCS = proj.c timer.c keyboard.c mouse.c graphics.c visuals.c devicesManager.c game.c asteroid.c rotation.c fireball.c gamePlay.c rtc.c highscores.c

CPPFLAGS += -pedantic #-D __LCOM_OPTIMIZED__

DPADD += ${LIBLCF}
LDADD += -llcf

.include <minix.lcom.mk>
